{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pod-time-controller.clusterRoleName" . }}
rules:
  - apiGroups: [ "" ]
    resources: [ pods ]
    verbs: [ get, list, watch, patch ]
      {{- end }}
